version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER:  admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB:       apple
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"      # binds container’s 5432 → host’s 5432

volumes:
  db-data:
